### ISSUE TITLE
Feature request: support dark themes

### ISSUE THREAD

**Issue by NickCraver** [xxhomey19/github-file-icon#34]
First: I love this extension!

I know the title is scary, but I propose a simplistic solution to make life better for dark GitHub users in a hurry. Here's what I'm doing locally:
```css
.icon .octicon:before {
    filter: brightness(125%) contrast(150%) drop-shadow(0 0 0 #fff) drop-shadow(1px 1px 1px #444);
}
```
I'm sure a designer could do far better than I, but something like this rigged to a "Dark Mode" checkbox in the options would make it super simple for those with dark themes to have much better looking icons.

Here's a compare on my machine of extension+dark vs. extension+dark+tweak above:
![compare](https://user-images.githubusercontent.com/454813/38455054-4a924cf4-3a40-11e8-86d6-29a030dfde49.jpg)

I think it's hard to tell in a 2:1 block up issue picture, but they're far more readable on a HiDPI screen. I'm not saying use my styling (though you're welcome to), but I just wanted to pitch the idea in general: a checkbox hooked to a CSS tweak to improve life a bit.

Thoughts?
